=== olecrab/Fincas_Mallorca/xml/finca.dtd
<!ELEMENT fincas (finca*)>
<!ELEMENT finca (codi, codi_propietari, tipo, nombre, imagenes, descripcion, poblacion, coordenadas, capcidad_personas, metros_casa, metros_terreno, num_habitaciones, num_banyos, servicios?, hora, calendario, precio, comentarios?)>

<!ELEMENT tipo (finc?, casa?, apartamento?)>
<!ELEMENT imagenes (url+)>
<!ELEMENT coordenadas (longitud, latitud)>
<!ELEMENT servicios (internet?, piscina?, limpieza?, climatizacion?, television?, lavadora?, barbaco?, cocina)>
<!ELEMENT cocina (tostadora?, horno?, lavavajillas?, cafetera?, microondas?, nevera?, congelador?)>
<!ELEMENT hora (entrada, salida)>
<!ELEMENT calendario (registre*)>
<!ELEMENT registre (dia, mes, any, ndias)>
<!ELEMENT precio (enero, febrero, marzo, abril, mayo, junio, julio, agosto, septiembre, octubre, noviembre, diciembre)>
<!ELEMENT comentarios (comentario*)>
<!ELEMENT comentario (name, opinon, valoracion)>

<!ELEMENT codi (#PCDATA)>
<!ELEMENT codi_propietari (#PCDATA)>
<!ELEMENT finc (#PCDATA)>
<!ELEMENT casa (#PCDATA)>
<!ELEMENT apartament (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>
<!ELEMENT longitud (#PCDATA)>
<!ELEMENT latitud (#PCDATA)>
<!ELEMENT capacidad_personas (#PCDATA)>
<!ELEMENT metros_casa (#PCDATA)>
<!ELEMENT metros_terreno (#PCDATA)>
<!ELEMENT num_habitaciones (#PCDATA)>
<!ELEMENT num_banyos (#PCDATA)>
<!ELEMENT internet (#PCDATA)>
<!ELEMENT piscina (#PCDATA)>
<!ELEMENT limpieza (#PCDATA)>
<!ELEMENT climatizacion (#PCDATA)>
<!ELEMENT television (#PCDATA)>
<!ELEMENT lavadora (#PCDATA)>
<!ELEMENT barbacoa (#PCDATA)>
<!ELEMENT tostadora (#PCDATA)>
<!ELEMENT horno (#PCDATA)>
<!ELEMENT lavavajillas (#PCDATA)>
<!ELEMENT cafetera (#PCDATA)>
<!ELEMENT microonadas (#PCDATA)>
<!ELEMENT nevera (#PCDATA)>
<!ELEMENT congelador (#PCDATA)>
<!ELEMENT entrada (#PCDATA)>
<!ELEMENT salida (#PCDATA)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT any (#PCDATA)>
<!ELEMENT ndias (#PCDATA)>
<!ELEMENT enero (#PCDATA)>
<!ELEMENT febrero (#PCDATA)>
<!ELEMENT marzo (#PCDATA)>
<!ELEMENT abril (#PCDATA)>
<!ELEMENT mayo (#PCDATA)>
<!ELEMENT junio (#PCDATA)>
<!ELEMENT julio (#PCDATA)>
<!ELEMENT agosto (#PCDATA)>
<!ELEMENT septiembre (#PCDATA)>
<!ELEMENT octubre (#PCDATA)>
<!ELEMENT noviembre (#PCDATA)>
<!ELEMENT diciembre (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT opinion (#PCDATA)>
<!ELEMENT valoracion (#PCDATA)>

=== olecrab/Fincas_Mallorca/xml/fincas.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/xsl"?>
<!DOCTYPE fincas SYSTEM "xml/finca.dtd">
<fincas>
  <finca>
    <codi>0</codi>
    <codi_propietari>1</codi_propietari>
    <tipo>
      <casa>1</casa>
    </tipo>
    <nombre>Oasis</nombre>
    <imagenes>
      <url>img/img_fincas/oasis/img/img0.jpg</url>
      <url>img/img_fincas/oasis/img/img1.jpg</url>
      <url>img/img_fincas/oasis/img/img2.jpg</url>
      <url>img/img_fincas/oasis/img/img3.jpg</url>
      <url>img/img_fincas/oasis/img/img4.jpg</url>
      <url>img/img_fincas/oasis/img/img5.jpg</url>
      <url>img/img_fincas/oasis/img/img6.jpg</url>
      <url>img/img_fincas/oasis/img/img7.jpg</url>
      <url>img/img_fincas/oasis/img/img8.jpg</url>
      <url>img/img_fincas/oasis/img/img9.jpg</url>
      <url>img/img_fincas/oasis/img/img10.jpg</url>
      <url>img/img_fincas/oasis/img/img11.jpg</url>
      <url>img/img_fincas/oasis/img/img12.jpg</url>
      <url>img/img_fincas/oasis/img/img13.jpg</url>
      <url>img/img_fincas/oasis/img/img14.jpg</url>
      <url>img/img_fincas/oasis/img/img15.jpg</url>
    </imagenes>
    <descripcion>
      La propiedad es del siglo XI y desde el siglo XV es propiedad de la misma familia, y es de momento una de las pocas propiedades de ese tamaño que están disponibles exclusivamente en el mercado.

      El terreno con 2.882,9 hectáreas a los pies de Tramuntana cerca de Caimairi-Binibona en la comunidad de Selva incluye varias superficies de uso agrícola así como la histórica propiedad con más de 2.000 metros cuadrados de superficie habitable total, dividida en varios edificios, terrazas y piscina, así como una residencia privada e independiente de 400 metros cuadrados. 

      El terreno puede funcionar lucrativamente o ser usado como un idilio muy privado en Mallorca. 

      Las vistas y el entorno son soñados, usted entra en un mundo de antaño, en el que los secretos de las generaciones están firmemente anclados en los gruesos muros de piedra que lo componen. Cruce el patio adoquinado pasando por las fuentes medievales y admire las Almanzaras (2 prensas de aceite están disponibles) y descubra una sensación de vida nueva y original en la isla.
    </descripcion>
    <poblacion>Santa Eugènia</poblacion>
    <coordenadas>
      <longitud>2.847707</longitud>
      <latitud>39.618571</latitud>
    </coordenadas>
    <capacidad_personas>12</capacidad_personas>
    <metros_casa>300</metros_casa>
    <metros_terreno>2000</metros_terreno>
    <num_habitaciones>8</num_habitaciones>
    <num_banyos>8</num_banyos>
    <servicios>
      <piscina>Piscina</piscina>
      <climatizacion>Climatizacion</climatizacion>
      <barbacoa>Barbacoa</barbacoa>
      <cocina>
        <tostadora>1</tostadora>
        <horno>1</horno>
        <nevera>1</nevera>
        <congelador>1</congelador>
      </cocina>
    </servicios>
    <hora>
      <entrada>14:00</entrada>
      <salida>10:00</salida>
    </hora>
    <calendario>
    </calendario>
    <precio>
      <enero>80</enero>
      <febrero>80</febrero>
      <marzo>90</marzo>
      <abril>90</abril>
      <mayo>100</mayo>
      <junio>100</junio>
      <julio>150</julio>
      <agosto>150</agosto>
      <septiembre>100</septiembre>
      <octubre>100</octubre>
      <noviembre>80</noviembre>
      <diciembre>80</diciembre>
    </precio>
    <comentarios>
    </comentarios>
  </finca>
  <finca>
    <codi>1</codi>
    <codi_propietari>1</codi_propietari>
    <tipo>
      <finc>1</finc>
      <casa>1</casa>
    </tipo>
    <nombre>Casa del Mar</nombre>
    <imagenes>
      <url>img/img_fincas/Casa_Del_Mar/img/img0.jpg</url>
      <url>img/img_fincas/Casa_Del_Mar/img/img1.jpg</url>
      <url>img/img_fincas/Casa_Del_Mar/img/img2.jpg</url>
      <url>img/img_fincas/Casa_Del_Mar/img/img3.jpg</url>
      <url>img/img_fincas/Casa_Del_Mar/img/img4.jpg</url>
      <url>img/img_fincas/Casa_Del_Mar/img/img5.jpg</url>
      <url>img/img_fincas/Casa_Del_Mar/img/img6.jpg</url>
      <url>img/img_fincas/Casa_Del_Mar/img/img7.jpg</url>
      <url>img/img_fincas/Casa_Del_Mar/img/img8.jpg</url>
      <url>img/img_fincas/Casa_Del_Mar/img/img9.jpg</url>
      <url>img/img_fincas/Casa_Del_Mar/img/img10.jpg</url>
      <url>img/img_fincas/Casa_Del_Mar/img/img11.jpg</url>
    </imagenes>
    <descripcion>
      Esta finca espaciosa con vistas al mar está ubicada en Ses Salines (el centro se alcanza a pie) y es idónea para familias grandes. 

      La superficie habitable de aprox. 230 metros cuadrados está dividida en 6 dormitorios, 4 baños, biblioteca, salón, comedor y una cocina. Además, la propiedad ofrece un apartamento de invitados integrado y uno separado, lo que ofrece muchas posibilidades como por ejemplo el alquiler vacacional.

      En el exterior encontramos una piscina preciosa con vistas al jardín así como un establo. 

      Esta finca ofrece todas las comodidades y está equipada con suelos de mármol y calefacción.
      Lugar y alrededores:
      Ses Salines es uno de los pueblos más bonitos y antiguos en la costa sureste de Mallorca. La imagen del pueblo se caracteriza por los agradables bares y restaurantes donde mallorquines y turistas toman su café con leche al disfrutar del sol. 

      Es un pueblo típico mallorquín que recibe su nombre de las salinas del tiempo romano. Hasta la fecha se cosecha sal de ellas. Los talayotes, vestigios de un asentamiento prehistórico, también son muy interesantes. 

      Muchas calas pequeñas como la de Cala Llombards y la playas natural de Es Trenc están a pocos minutos en coche. También puede descubrir el paisaje precioso y plano con la bicicleta.

      Este mapa muestra la situación de la propiedad en la visión general. Mallorca. Hemos recopilado una selección de las Playas, Campos de golf, Puertos Deportivos y Restaurantes más atractivos.
    </descripcion>
    <poblacion>Son Serra</poblacion>
    <coordenadas>
      <longitud>3.223770</longitud>
      <latitud>39.737699</latitud>
    </coordenadas>
    <capacidad_personas>5</capacidad_personas>
    <metros_casa>120</metros_casa>
    <metros_terreno>1300</metros_terreno>
    <num_habitaciones>4</num_habitaciones>
    <num_banyos>5</num_banyos>
    <servicios>
      <internet>Internet</internet>
      <piscina>Piscina</piscina>
      <television>TV</television>
      <barbacoa>Barbacoa</barbacoa>
    </servicios>
    <calendario>
    </calendario>
    <precio>
      <enero>100</enero>
      <febrero>110</febrero>
      <marzo>110</marzo>
      <abril>150</abril>
      <mayo>160</mayo>
      <junio>180</junio>
      <julio>200</julio>
      <agosto>200</agosto>
      <septiembre>180</septiembre>
      <octubre>160</octubre>
      <noviembre>150</noviembre>
      <diciembre>140</diciembre>
    </precio>
    <comentarios>
    </comentarios>
  </finca>
  <finca>
    <codi>2</codi>
    <codi_propietari>2</codi_propietari>
    <tipo>
      <finc>1</finc>
      <apartamento>1</apartamento>
    </tipo>
    <nombre>Hort Riu</nombre>
    <imagenes>
      <url>img/img_fincas/Hort_Riu/img/img0.jpg</url>
      <url>img/img_fincas/Hort_Riu/img/img1.jpg</url>
      <url>img/img_fincas/Hort_Riu/img/img2.jpg</url>
      <url>img/img_fincas/Hort_Riu/img/img3.jpg</url>
      <url>img/img_fincas/Hort_Riu/img/img4.jpg</url>
      <url>img/img_fincas/Hort_Riu/img/img5.jpg</url>
      <url>img/img_fincas/Hort_Riu/img/img6.jpg</url>
      <url>img/img_fincas/Hort_Riu/img/img7.jpg</url>
      <url>img/img_fincas/Hort_Riu/img/img8.jpg</url>
      <url>img/img_fincas/Hort_Riu/img/img9.jpg</url>
      <url>img/img_fincas/Hort_Riu/img/img10.jpg</url>
      <url>img/img_fincas/Hort_Riu/img/img11.jpg</url>
      <url>img/img_fincas/Hort_Riu/img/img12.jpg</url>
      <url>img/img_fincas/Hort_Riu/img/img13.jpg</url>
      <url>img/img_fincas/Hort_Riu/img/img14.jpg</url>
      <url>img/img_fincas/Hort_Riu/img/img15.jpg</url>
    </imagenes>
    <descripcion>
      Esta finca exclusiva está a pocos metros de la famosa playa de ensueño de Es Trenc, en medio de un solar con vegetación mediterránea y por lo tanto con mucha privacidad, en la reserva natural entre Sa Rapita y Ses Covetes. Es un curiosidad tener la posibilidad de comprar una finca tan espaciosa y tan cerca de Es Trenc.

      La propiedad consiste de una villa con un apartamento de invitados separado así como de 2 casas para invitados más pequeñas. El área de la piscina de aprox. 150 metros cuadrados está ubicada en el centro y ofrece una cascada, un jacuzzi y un bar rodeado de palmeras. 

      La casa principal al estilo colonial español de aprox. 150 metros cuadrados con algunos muebles antiguos dispone de un salón, 2 dormitorios, un comedor con una cocina abierta y un baño. La casa ha sido equipada con mucho amor a materiales clásicos como el mármol, la piedra y la madera. Aquí también encuentra el acceso a la bodega. Terrazas grandes y abiertas, todas orientadas hacia la piscina, completan la casa principal.

      Con una entrada separada sobre la vivienda principal, usted encuentra un piso pequeño en la planta superior que consta de un salón, comedor y un baño así como de una terraza propia para ahí poder pasar horas agradables.

      La casa de invitados original al estilo mallorquín en aprox. 40 metros cuadrados ofrece una cocina con un dormitorio separado, un baño y una terraza pequeña. La otra casa de invitados está un poco apartado y en una superficie total de aprox. 70 metros cuadrados comprende 2 dormitorios, 2 baños y otro salón con una cocina abierta que ha sido bien diseñada y ofrece una chimenea abierta y un lagar antiguo. 

      En el extremo del solar encontramos establos a reformar con un prado pequeño para 2 caballos con los que directamente puede montar a caballo en las dunas de Es Trenc.
